### PR TITLE
Mobile app react

### PR DESCRIPTION
**Pull request by mezgoodle**

### CODE REVIEW

**Comment by mezgoodle** [comment]
[Workflow](https://github.com/marketplace/actions/react-native-android-build-apk) to build APK

**Comment by mezgoodle** [comment]
How to build - [article](https://stackoverflow.com/questions/44301539/react-native-generate-apk-and-ipa-using-expo)

**Comment by mezgoodle** [comment]
Preview

**Comment by mezgoodle** [comment]
Now you can do review, but i have next tasks:

- [ ] Set CI with linter and maybe tests

**Review by VsIG-official — APPROVED** [review]

**Comment by mezgoodle** [comment]
I added linter, but can't to **write unit-tests** cause of lack of knowledge of _React Native_

**Review by Dmytrenko-Roman — APPROVED** [review]

**Pull request merged**
