### PR TITLE
Mobile App

### PR DESCRIPTION
**Pull request by mezgoodle**
Create project in PyCharm

### CODE REVIEW

**Comment by mezgoodle** [comment]
@VsIG-official 
I have written some logic, please look through it, make code-review

**Review by VsIG-official — COMMENTED** [review]
This part of code looks good and I don't have suggestions about it

**Comment by mezgoodle** [comment]
- [Link](https://expo.io/accounts/mezgoodle/builds/2143cb1e-36c0-46fe-ae40-f5ef44ff8964) to get Android APK
- For IOS I can't build because I don't have Apple account

**Comment by VsIG-official** [comment]
I need an account to get apk file. Can You just upload it on github?

**Comment by mezgoodle** [comment]
> I need an account to get apk file. Can You just upload it on github?

[Here](https://drive.google.com/file/d/1eMO3JIG1fjIOoQEyOC25am-Ccb87QVPp/view?usp=sharing)

**Comment by VsIG-official** [comment]
image
image

icon is small, but everything else is OK

**Review by VsIG-official — APPROVED** [review]

**Review by VsIG-official — CHANGES_REQUESTED** [review]
Change icon size

**Comment by mezgoodle** [comment]
> Change icon size

Try [this](https://drive.google.com/file/d/1fa6YyXU0BaUSUQgVJcLnJfks05bm0qv8/view?usp=sharing)

**Comment by VsIG-official** [comment]
Still the same

**Comment by mezgoodle** [comment]
> Still the same

photo_2021-05-21_10-31-06

**Comment by VsIG-official** [comment]
then it depends on mobile device

**Review by VsIG-official — APPROVED** [review]

**Comment by mezgoodle** [comment]
Now in the app there are some links-placeholders for API, when we deployed Django, I will change them. Also app will not work without Internet access. I think we can write it in README later. We will not deployed our mobile app in the Play Market, apk will be in releases, and I think it's better

**Comment by VsIG-official** [comment]
But why not deploying apk on play market is better?

**Comment by mezgoodle** [comment]
> But why not deploying apk on play market is better?

Actually I didn't never do it, and don't have experience

**Comment by VsIG-official** [comment]
Well, I can take it on Myself.
I need account for it for 25$, but I will buy it in the future anyway, so it doesn't matter.

**Comment by mezgoodle** [comment]
> Well, I can take it on Myself.
> I need account for it for 25$, but I will buy it in the future anyway, so it doesn't matter.

As you wish. Our organization don't have money yet, so...

**Pull request merged**
