### PR TITLE
CU-85ztcygf2_Improve-code-coverage

### PR DESCRIPTION
**Pull request by mezgoodle**
Get code-coverage from both sides at once

### CODE REVIEW

**Comment by mezgoodle** [comment]
Task linked: [CU-85ztcygf2 Improve code coverage](https://app.clickup.com/t/85ztcygf2)

**Comment by mezgoodle** [comment]
Мене дивує, що сервіс деплою fastapi мовчить(

**Comment by mezgoodle** [comment]
> ## [Codecov](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia) Report
> > Merging [#228](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia) ([eddb53d](https://github.com/mezidia/song-helper/commit/eddb53d02d7c195d6eaa4d1a79c63636ecab6670)) into [rebuild](https://app.codecov.io/gh/mezidia/song-helper/commit/e5961f4f1a6bd258c6e860c760115c154026abb7?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia) ([e5961f4](https://github.com/mezidia/song-helper/commit/e5961f4f1a6bd258c6e860c760115c154026abb7)) will **increase** coverage by `0.68%`.
> > The diff coverage is `98.82%`.
> 
> ```diff
> @@             Coverage Diff             @@
> ##           rebuild     #228      +/-   ##
> ===========================================
> + Coverage    97.36%   98.05%   +0.68%     
> ===========================================
>   Files           19       17       -2     
>   Lines          304      411     +107     
> ===========================================
> + Hits           296      403     +107     
>   Misses           8        8              
> ```
> 
> [Impacted Files](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia)	Coverage Δ	
> [server/tests/test_authentication.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3Rlc3RzL3Rlc3RfYXV0aGVudGljYXRpb24ucHk=)	`89.65% <89.65%> (+0.36%)`	⬆️
> [server/src/routers/authentication.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9yb3V0ZXJzL2F1dGhlbnRpY2F0aW9uLnB5)	`96.87% <96.87%> (+0.57%)`	⬆️
> [server/src/authentication.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9hdXRoZW50aWNhdGlvbi5weQ==)	`100.00% <100.00%> (ø)`	
> [server/src/database.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9kYXRhYmFzZS5weQ==)	`100.00% <100.00%> (ø)`	
> [server/src/dependencies.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9kZXBlbmRlbmNpZXMucHk=)	`88.46% <100.00%> (ø)`	
> [server/src/main.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9tYWluLnB5)	`100.00% <100.00%> (ø)`	
> [server/src/routers/requests.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9yb3V0ZXJzL3JlcXVlc3RzLnB5)	`100.00% <100.00%> (ø)`	
> [server/src/routers/users.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9yb3V0ZXJzL3VzZXJzLnB5)	`100.00% <100.00%> (ø)`	
> [server/src/schemas.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9zY2hlbWFzLnB5)	`100.00% <100.00%> (ø)`	
> [server/tests/test_auth_utils.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3Rlc3RzL3Rlc3RfYXV0aF91dGlscy5weQ==)	`100.00% <100.00%> (ø)`	
> ... and [3 more](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree-more&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia)		
> ... and [4 files with indirect coverage changes](https://app.codecov.io/gh/mezidia/song-helper/pull/228/indirect-changes?src=pr&el=tree-more&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia)
> 
> 📣 We’re building smart automated test selection to slash your CI/CD build times. [Learn more](https://about.codecov.io/iterative-testing/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia)

@MaksGovor , @VsIG-official  , як думаєте, що таке indirect changes? На сайті пишеться "These are files that didn't have author revisions, but contain unexpected coverage changes"

**Comment by mezgoodle** [comment]
> > ## [Codecov](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia) Report
> > > Merging [#228](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia) ([eddb53d](https://github.com/mezidia/song-helper/commit/eddb53d02d7c195d6eaa4d1a79c63636ecab6670)) into [rebuild](https://app.codecov.io/gh/mezidia/song-helper/commit/e5961f4f1a6bd258c6e860c760115c154026abb7?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia) ([e5961f4](https://github.com/mezidia/song-helper/commit/e5961f4f1a6bd258c6e860c760115c154026abb7)) will **increase** coverage by `0.68%`.
> > > The diff coverage is `98.82%`.
> > 
> > 
> > ```diff
> > @@             Coverage Diff             @@
> > ##           rebuild     #228      +/-   ##
> > ===========================================
> > + Coverage    97.36%   98.05%   +0.68%     
> > ===========================================
> >   Files           19       17       -2     
> >   Lines          304      411     +107     
> > ===========================================
> > + Hits           296      403     +107     
> >   Misses           8        8              
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [Impacted Files](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia)	Coverage Δ
> > [server/tests/test_authentication.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3Rlc3RzL3Rlc3RfYXV0aGVudGljYXRpb24ucHk=)	`89.65% <89.65%> (+0.36%)`	⬆️
> > [server/src/routers/authentication.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9yb3V0ZXJzL2F1dGhlbnRpY2F0aW9uLnB5)	`96.87% <96.87%> (+0.57%)`	⬆️
> > [server/src/authentication.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9hdXRoZW50aWNhdGlvbi5weQ==)	`100.00% <100.00%> (ø)`
> > [server/src/database.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9kYXRhYmFzZS5weQ==)	`100.00% <100.00%> (ø)`
> > [server/src/dependencies.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9kZXBlbmRlbmNpZXMucHk=)	`88.46% <100.00%> (ø)`
> > [server/src/main.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9tYWluLnB5)	`100.00% <100.00%> (ø)`
> > [server/src/routers/requests.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9yb3V0ZXJzL3JlcXVlc3RzLnB5)	`100.00% <100.00%> (ø)`
> > [server/src/routers/users.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9yb3V0ZXJzL3VzZXJzLnB5)	`100.00% <100.00%> (ø)`
> > [server/src/schemas.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9zY2hlbWFzLnB5)	`100.00% <100.00%> (ø)`
> > [server/tests/test_auth_utils.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3Rlc3RzL3Rlc3RfYXV0aF91dGlscy5weQ==)	`100.00% <100.00%> (ø)`
> > ... and [3 more](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree-more&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia)
> > ... and [4 files with indirect coverage changes](https://app.codecov.io/gh/mezidia/song-helper/pull/228/indirect-changes?src=pr&el=tree-more&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia)
> > 📣 We’re building smart automated test selection to slash your CI/CD build times. [Learn more](https://about.codecov.io/iterative-testing/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia)
> 
> @MaksGovor , як думаєш, що таке indirect changes? На сайті пишеться "These are files that didn't have author revisions, but contain unexpected coverage changes"

Хоча тут добре видно, що і сервер є, і клієнт, що було задачею нашою

image

**Comment by MaksGovor** [comment]
> > ## [Codecov](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia) Report
> > > Merging [#228](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia) ([eddb53d](https://github.com/mezidia/song-helper/commit/eddb53d02d7c195d6eaa4d1a79c63636ecab6670)) into [rebuild](https://app.codecov.io/gh/mezidia/song-helper/commit/e5961f4f1a6bd258c6e860c760115c154026abb7?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia) ([e5961f4](https://github.com/mezidia/song-helper/commit/e5961f4f1a6bd258c6e860c760115c154026abb7)) will **increase** coverage by `0.68%`.
> > > The diff coverage is `98.82%`.
> > 
> > 
> > ```diff
> > @@             Coverage Diff             @@
> > ##           rebuild     #228      +/-   ##
> > ===========================================
> > + Coverage    97.36%   98.05%   +0.68%     
> > ===========================================
> >   Files           19       17       -2     
> >   Lines          304      411     +107     
> > ===========================================
> > + Hits           296      403     +107     
> >   Misses           8        8              
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [Impacted Files](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia)	Coverage Δ
> > [server/tests/test_authentication.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3Rlc3RzL3Rlc3RfYXV0aGVudGljYXRpb24ucHk=)	`89.65% <89.65%> (+0.36%)`	arrow_up
> > [server/src/routers/authentication.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9yb3V0ZXJzL2F1dGhlbnRpY2F0aW9uLnB5)	`96.87% <96.87%> (+0.57%)`	arrow_up
> > [server/src/authentication.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9hdXRoZW50aWNhdGlvbi5weQ==)	`100.00% <100.00%> (ø)`
> > [server/src/database.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9kYXRhYmFzZS5weQ==)	`100.00% <100.00%> (ø)`
> > [server/src/dependencies.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9kZXBlbmRlbmNpZXMucHk=)	`88.46% <100.00%> (ø)`
> > [server/src/main.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9tYWluLnB5)	`100.00% <100.00%> (ø)`
> > [server/src/routers/requests.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9yb3V0ZXJzL3JlcXVlc3RzLnB5)	`100.00% <100.00%> (ø)`
> > [server/src/routers/users.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9yb3V0ZXJzL3VzZXJzLnB5)	`100.00% <100.00%> (ø)`
> > [server/src/schemas.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9zY2hlbWFzLnB5)	`100.00% <100.00%> (ø)`
> > [server/tests/test_auth_utils.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3Rlc3RzL3Rlc3RfYXV0aF91dGlscy5weQ==)	`100.00% <100.00%> (ø)`
> > ... and [3 more](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree-more&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia)
> > ... and [4 files with indirect coverage changes](https://app.codecov.io/gh/mezidia/song-helper/pull/228/indirect-changes?src=pr&el=tree-more&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia)
> > mega We’re building smart automated test selection to slash your CI/CD build times. [Learn more](https://about.codecov.io/iterative-testing/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia)
> 
> @MaksGovor , @VsIG-official , як думаєте, що таке indirect changes? На сайті пишеться "These are files that didn't have author revisions, but contain unexpected coverage changes"

Мені здається, що це файли в котрі не вносились зміни, але покриття їх тестами змінилось, наприклад змінили сам тест, і змінивсь через це відсток покриття.

**Review by MaksGovor — APPROVED** [review]

**Comment by mezgoodle** [comment]
> > > ## [Codecov](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia) Report
> > > > Merging [#228](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia) ([eddb53d](https://github.com/mezidia/song-helper/commit/eddb53d02d7c195d6eaa4d1a79c63636ecab6670)) into [rebuild](https://app.codecov.io/gh/mezidia/song-helper/commit/e5961f4f1a6bd258c6e860c760115c154026abb7?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia) ([e5961f4](https://github.com/mezidia/song-helper/commit/e5961f4f1a6bd258c6e860c760115c154026abb7)) will **increase** coverage by `0.68%`.
> > > > The diff coverage is `98.82%`.
> > > 
> > > 
> > > ```diff
> > > @@             Coverage Diff             @@
> > > ##           rebuild     #228      +/-   ##
> > > ===========================================
> > > + Coverage    97.36%   98.05%   +0.68%     
> > > ===========================================
> > >   Files           19       17       -2     
> > >   Lines          304      411     +107     
> > > ===========================================
> > > + Hits           296      403     +107     
> > >   Misses           8        8              
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > [Impacted Files](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia)	Coverage Δ
> > > [server/tests/test_authentication.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3Rlc3RzL3Rlc3RfYXV0aGVudGljYXRpb24ucHk=)	`89.65% <89.65%> (+0.36%)`	arrow_up
> > > [server/src/routers/authentication.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9yb3V0ZXJzL2F1dGhlbnRpY2F0aW9uLnB5)	`96.87% <96.87%> (+0.57%)`	arrow_up
> > > [server/src/authentication.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9hdXRoZW50aWNhdGlvbi5weQ==)	`100.00% <100.00%> (ø)`
> > > [server/src/database.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9kYXRhYmFzZS5weQ==)	`100.00% <100.00%> (ø)`
> > > [server/src/dependencies.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9kZXBlbmRlbmNpZXMucHk=)	`88.46% <100.00%> (ø)`
> > > [server/src/main.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9tYWluLnB5)	`100.00% <100.00%> (ø)`
> > > [server/src/routers/requests.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9yb3V0ZXJzL3JlcXVlc3RzLnB5)	`100.00% <100.00%> (ø)`
> > > [server/src/routers/users.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9yb3V0ZXJzL3VzZXJzLnB5)	`100.00% <100.00%> (ø)`
> > > [server/src/schemas.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3NyYy9zY2hlbWFzLnB5)	`100.00% <100.00%> (ø)`
> > > [server/tests/test_auth_utils.py](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia#diff-c2VydmVyL3Rlc3RzL3Rlc3RfYXV0aF91dGlscy5weQ==)	`100.00% <100.00%> (ø)`
> > > ... and [3 more](https://app.codecov.io/gh/mezidia/song-helper/pull/228?src=pr&el=tree-more&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia)
> > > ... and [4 files with indirect coverage changes](https://app.codecov.io/gh/mezidia/song-helper/pull/228/indirect-changes?src=pr&el=tree-more&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia)
> > > mega We’re building smart automated test selection to slash your CI/CD build times. [Learn more](https://about.codecov.io/iterative-testing/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mezidia)
> > 
> > 
> > @MaksGovor , @VsIG-official , як думаєте, що таке indirect changes? На сайті пишеться "These are files that didn't have author revisions, but contain unexpected coverage changes"
> 
> Мені здається, що це файли в котрі не вносились зміни, але покриття їх тестами змінилось, наприклад змінили сам тест, і змінивсь через це відсток покриття.

або новий репорт прийшов

**Review by VsIG-official — APPROVED** [review]
Nice tests, big coverage

**Comment by mezgoodle** [comment]
> Nice tests, big coverage

А що думаєш щодо indirect changes? Як це перекласти?

**Pull request merged**
